sequence = "GACGGTAGGCGGTAGGCCCTGGTAGGCACGGTAGGCGGTAGGCCAGTTGGTAGGCGGTAGGCTCGGTAGGCGGTAGGCCCAGGTAGGCCGGTAGGCACGGTAGGCGGTAGGCCGGGTAGGCACTGGTAGGCACGGGTAGGCTTGGTAGGCGGTAGGCGGTAGGCGGTAGGCCTGGGGTAGGCGGTAGGCGGTAGGCACCCGGTAGGCCGGTAGGCGGGTAGGCAGGTAGGCGGTAGGCGCGAGGAACGGTAGGCTAGGTAGGCGTTGGTAGGCTGGGTAGGCCTATGGTAGGCTGGTAGGCGGTAGGCATTAGATTGCTGGTAGGCGGTAGGCAAGGTAGGCTAGTGGTAGGCAGGTAGGCGGGTAGGCAGGTAGGCGCGGTAGGCGCCACCTGGGGATGGTAGGCGAGGTAGGCTACCAGGTAGGCCGGTCGGTAGGCAACGGTAGGCGGTAGGCAGGTAGGCACAAGGTAGGCAGAGCGGGTAGGCAGGTAGGCAAAAACCGGTCGGTAGGCGTGCTGGTAGGCGGGTAGGCTGGGTAGGCCGGTAGGCGGTAGGCAGAAGGTAGGCGGTAGGCGCGGTAGGCAAACGGTAGGCGAGGTAGGCTTGAACGGTAGGCGGAGGTAGGCGGTAGGCAGGTAGGCATGGTAGGCGGGTAGGCTCGGACGGTAGGCCGGTAGGCCGGTAGGCCGGTAGGCGGTAGGCTCCGGTAGGCGTAGGGTAGGCTGACGGGTAGGCGGTAGGCGGTAGGCAGCGGTAGGCCCAAACCGGTAGGCACGGTAGGCGGCGAAGCAGGTAGGCAATCAAATGGGTAGGCGTTAGGTAGGCCAGGTAGGCGGTAGGCGGTAGGCGGTAGGCGTGGAGGTAGGCAGGTAGGCTAGCTCCGGTAGGCGGGTAGGCTCGGAGGTAGGCCTTCGGTAGGCAATGGTAGGCGAGTC"

sql = list(sequence)

def finder(x):
    
    code = []
    for z in range(0, (len(x)-9)):
        if x[z] == 'G':
            if x[z+1] == 'G':
                if x[z+2] == 'T':
                    if x[z+3] == 'A':
                        if x[z+4] == 'G':
                            if x[z+5] == 'G':
                                if x[z+6] == 'C':
                                    if x[z+7] == 'G':
                                        if x[z+8] == 'G':
                                            code.append(z+1)  

    print((''.join(str(code))).replace(',', ' '))

finder(sql)