from tracemalloc import stop


code = 'AUGUUGCCUGUAAUUUUAGGAGUAUUGAUGCGUGAUCGGAAAGCACAUACCCAACGCCUACACAGUGGGCUACGUAAGACGGCGUCCUUCGCAUACGCCAUCUUAUGUAUCACCUAUGGAUCUGGAAAUAGCUCAACUGGGAGGCAAGAUGACUCGCUCUACCGUAACAGUUCAGGAGUCGUAAAGCUGAAUAAUGAAAGGAAGACUUCUCGCUCCUCUGGUGCAAAGCUCAGGUCUAACGCUCUAUGUUUUAUGACGACUGAAAGGGCGCCCGGUGACAAAAAUCGGUAUAUUUGUCCUAAGUAUAACCCAAAUCCUGAAAUGUACUUCCUAAUCCGCAUUUGGAGUAGGGGCCACACUCUGACACCUCUUGAAUGUGUCGACUCGUUCGCACGGGGGAAGAGUUUGUUAAGAGGCAGCUAUCGCUAUUUCCCCGAUCGGCCGGUUGUACCGAAUUCGACGACAGACAAGACACAUCAUAUCAGGGAGCGUCAGGGUAUUACAGUAACACGAGAGAGGAAAGGUGGUGAAAUUGCCUAUCCGCUCACGGCCUGUGGUAGGAAUCGUCAUGGGGGCGUCAGAUCUACGACGGGCUCAUCUUCAGAUGAGUACCUACGCGGUCGAGUAGGUACGGUCGACGGAUCAGCCCCCAAAUGCGGGCACGCCGUCUCGCGGAAUGCAUUUCGAGACAGCACCAGGAUACGAGCCCCGUUAACGACUUUAAAGCAACGGCUAGCCGGGCCCUAUACGAACGUGCCGUCAAAGUUCGAACGCAUACGUAGGUUUGUGGCAGCUAUAACUACAAACAAAGCGGAUGAAUGGUCAUAUGUCCGCAAGGUUCCCUACAGCUUCAGACCCGUAAGUGUGGUGCAAACACUUUCGCGCAGUCCAUUCCGUAGACCAUUCAUAAUGUAUAAUGUGCGAGGGUUAAAAGAUCCAGAAUGCCCGCCCUCUUCUGUGUCCAGGCUCUGCUCGAUGCCUGCCACGGCCGUCAUAAUUAACCCCCCCUUGACACAAGGUGGGGGGCUAAUAGGGGAUACUGUUUCUUUAUUCCGAUGCCCAGCCGCAUACGGUCGGCAUAUAUGCCUGAGCUCAAGGGGGCGGGCUCGGCAGUGCACGAUAUGUCAAAUCGUAUUCAACCUAGUUCAGAUUCCACUCCCCGUACCCGAGAGUGGCGAUGCGUCGCCAAAUCGUUACCGGCUAGUGCGGGUUGACUGUAGAUCGCUUCAGUUCGAAGGGCAUUCGGCAAGCCACGGUAUGCGUUCAAUCGUGCAACACGUGGGGGUCGUUGGGACGUUCCCGUAUCUGGCGUGUCAGCAGUCGCCGACGUUUGGUAGCGCCAGAGCGCGGCCUGGACGCUCAUCCUUGAACCCCUUUCAACCUACCACCGACCCUCACCCCAGACAUACUGAUAUACAGAGACGCAACUGGGGCGCCCUCUGUAUAUCGGUCUUCUCGUAUUUUACGUGCCUAGCAAAGGGCCCGACACCCCGCGGACCCCUUGGGAGCGUCACGGCGUCACGAGGGAAUCAUAGGUCGGCGCAUUACCUUGUCGGUUUCUGCAAGGGCCGAUCGUUGGAUCUGGUCUCAGUAAAUGGAGUGACUGUUUUUAAAGCAGGCCGGCUUGCAGUUCCCGCGGGAUCGAACUCCACCUCCCUGAUAACUCCGUACAGAUCAUGGGACGUUAAUAUGCACUCUGCAAAAUUCGAAGCUGCAAGGGCCAAUGAGGGACUCUCAUCCGGAUUAUCUUGGACUUGUACGGCUGGGUCCUGGUUGACUUUAGCUACCUGCGUCGCCCCGCACUAUUGUCAGUCACCGCCGUGGAUGCCCUGUGGUGUGCCGUUUUGCACCCUUUACACGAGCCGGUAUGCGUGUUGGAAAUUGAAGUGGUGGAUCGUCGAUCUUAAUACCACAGAAGGUCCCGGUGCAGAGGUUCAAUACAUACGGCUCGCUGGAAAUUUUCGGACGCCGAAGGAAUCCUUGUUCCAGUUAUGCUUCUAUAGGGGCUGGCUAGUUCACUAUGCCAAUCCUCGCUCCAAGGUAACCAAAUACCAAUACUUGGAGCGGGGCGACUUGCAGCUUAACAGUACAAGACUGGAACCUCAAUCUCAUAUACGUGCUCAAUUAACCGUUAAUAGAAUUAAAAGUGCCUGUUAUAUCAGUGACUGUGUGACGAGUCACACAGCCAUGCGACUAGGGGGUAAUGCGCUACGCCUCGACCAAACAAUGUCGGGCAUACGUGAAUGCGAUCGGCAGCGAAUCGUAAUGGAGAGGUAUACACGUAGGUGGUCGGAUGCUCGUGUUCCAUCACAGGCUUAUAUUAUUCAUAUGUCUGGGGUCCAUCUUAUUCAACAAACAUGGCACCAUUGUCGGGUUUGGGUGAUCAAAGUUUGCCGCCCCAUAUGUUACGUGCGGCAUGUGUCCCCAUACGCAAUGGAUGGCAAUGGACACGGGCACUUCUCACUUUCCAAGCGUCACGAGCGUGUGAACAAGCCGGUAUACCCAUUUCCCAUGCCAACAUGUUGCAAGCCUCGAGAAACCUCACGAGAUGGAUUCAAGCAAGGCCCCCUCCUCAGUAUUAUCGGAGAGAAAAAGUACCACCAUAUAAUUUUCGUCGAGAGAUCGCGGCCCCGUCCAGGCGCUGCGGCCAGGAACACGCAAGAAGCCUCGCAGGAUACUUAUAGGCGCGUGUGUGCGAGUGUGCCCUCCGGCUGUUUAUGGGGUUGGCCCUGCUUAGCGAUGGCUAUUGGCUAUACAAUACAUUUGUCCAUUCUGGUAACUUAUCUUGUGAAAAGAGUAUUCGUCUCAGUGCGGUGUAGCCCGGCUAGGUUGCGAUCUGGACCACUAUCCCAUGGAAGUAUAGCGCUUGCGGCCGCAUGCGUAUUCAGACAAUUACUGCAGGUUUGGGGCGAACCAACGCGUAAGUCUGCAGCCAGUAACAUAAGUCUGGGAGACUAUCAAUGCAAUAGGGUUCGAAGACAUCGAAGGCUGGAAGAUUUGCAGGCAUUAGCGGGUUCGAAUGGAUUCAGUGAAACUCCACACGUAGCGGCUAAGAUAUACAGCAAACUAUGUCUUGCGACUCGAAAGAUAGGAGAAGGUGCCUCCCGUGUCCUUCCGGCCGACUGUCGGCGGAAAUGCGGCACGCCUACGUGUUGCCGGACUCUAGAAAAUCUUGAUGGAGUUAAUCGGUAUGUGUAUAGAUUGUACGCCGUUACACGAGGACGUGAGAGGUGUCGGGGAGUCAACGUACUUCAGCGGAGUGCCUCCACAAGCCGGCUGCCACAAACGUUCUCCCGCGCCCUAGAGUUGCCGUGGAUUGCAACAAACACUGCAGCGCGACUGCGCCGCAAUUACGGAAGGUCCCAUGGUGACGUGGUGGCGGGCCUAUGUACAUCGGUAGCCCGGUGCACACUUGAGUUGUUUGUGUGGACUCACACGUGCAACGCGCAGUCCGAGGCCCUGGGAGUGCAACAUUUAACCGUUCAACGUGUUACUUACGAUACAUGGCUUCAUUAUCGCCUCCACCUACAGUCUGGCGCGGGUGGCCGAGGUGCACCAGUUUCGGUAAGGUGUUCGUCGGUAACAGAUAUGCGGUUGUACCCAUUUAAUAAGCUGCGCACGUUUGGGGAGCAGUACAACAUGCAUUCCGCAUGCACCAAGGCAAGAACCCAAUUAUUUUGUUCUGUCCACAUGAGGGCGCCAGGAGGGUUCUGGCCCCGCUCAAACCAAUCGGUCGGUAGCCAACCUUACGAUGCGUGGAGGCGAGACCCCACUUGCUACUCUUCUUGUACAUAUACUGGGAACUACCAUCCACGGAAUGACCUGAGGAAGCGUUGUAUGCCGGUGGCGACCGUUGAACCAAUACAUGUCAAAUCCUGUUUGCUCAGUCCAGGAAACGUGGUAAGUCCACGGAGGUUCGGAGAAAAGACCGCCCUGCAUCCCAUCCGAAUACGAGGUGCACGGUUAGUAGAUCUUGAACACUGGUCUUAUAGUAGUACUUACCACCAAGGGUCGCGCUGCCCGCCUACACGGCUGCAGGCUUAUCUCGUUCUAUCGAACGAAUGCGGAAAGCCGUAUUCCUCCUCCGGGUACCACCCGGCUAGGCCGUUAUCUGCCUGGAGUCAGCUCGUGGCUCCUCACGUGUUGGUAGAGAUACUACUUCUCUUUUUCCUUCUUCAAACCAUAACGGAUUGUGACGGUGGCUAUCAACUCGGAUUUAGACAGCCGCGACCCCUCGACGUCGUCGAAACCCUGACGGAACAGAACCGACACGUCAUUCUGCUUGAUGAAAACUCCAGCAGCACGACUGCCAUGGUUGGCAAUCCCAGCUAUUUAGGAGGAACAAUUGAGAUCAACGCCGGGAAAGAAUAUACCAGCCCUAAAGGUCCCUUCGCCGUCGUGUGGGUAAUCCACUGGCUCGAUCUAUAUCUUGUGAUAUGUGACAAUACACCAUGCACACUGCCAUAUGCACGGGAUUUUCUUGCUUCCCGCGGAGUUCUCAUAUCAAAUUCUAGUCCACCCGCAGGCGCGUCACAGCAACUGGUGUCAGUAGCAGUCUGUACGCGUAAGAUAACCCUGCGUCGGACAACGGUAGUGCAGGAAGAUAUCUUCCGAACUGGAUCCGGCACACAAUGCGUAGUGAGCAUCGGAGAAGGGUGUCGAGAAUUCCGAAAUCCGACGCUCAACAGCAAAUGCUAUCUUGUAUCUGUUCUUGUGCUACGACGAUCCUUCGAAACGGAUAGCCGCGUGAGUGCAUUGGCAUUUAAUAUGAAAGUCGGUCGGCGAACGAUCGCUCCCGGUUACGACAAAGUUCUGAAUACAGCUCCAACCGUUAACCUGGUCCUAGCUACACUGACUGUACUGAGAAGCAGCUGUAGGGCCUCUUCACUCCCCUACACGAGCGUACCACAUCCUAGAAUGCCUAACUUUCUGCAAUGCGGCUCGCUUGCAUGGCAACGAAUGCUGCGAUUGAUGCGUCAGGGCUUGCCCAAAUUUGGUCGACAGUCUGAGGCAUUGCGGUGCAUAUUCAACGCUAGGUCUCGGUGCGGAGGUACGGAACAACGCUCGUAUCGAGCACAGUUCGCAGCGGGAGAUCCGGCAACUAGCCCCCCGUUUACACUCUUCGAACUUCAAGAAAACUGUCCAACUCAAGGACGUGUCCAACCAGUUGUCAUCGUCUGGGUCUGUGUCAAGCGUGUAAAUAAUAACCACUCGAGCGGAGCCUUGUACGUACGGAUCUCAAAACUGAGGCGUAUGCGACCGCCGGGUUGCGAUGAUUCAUACGCCUGCUACUUUAGUGCAACGCCGUUCAUGACAGGCGGCGUGCGGAACGAAUUUAAGAAUAAGCAUGGGAAGGCCCUGCUGGGGGUCUCUACUGUGAGGAAAAAGCGCGAAAACGGGUCUGUUGGAUCAGCGUCUUAUCGUGAAUGUUGGCUAUCCUUCCAGCUGCACAAGCUCUGGACAGCAUGUCCAAGCAGUGCGGGAUCCGCCCCUUUCACAAGCCAGUCAAAUGGGUAUCUCCCAAACUCCCCGGGCUGUGGAUGUAUUUUCUAUAAGUGUCUCCAACGGGACACAUACAACGUACAGCAGGAUGUGGUAUCCCGAACGAAUCGGUCGAGCAACUUAGUUCACGGCUCAGCGCUUAGAGUUUCAGUUGCGACCCUGGUAUCUGGAAAUACUGUGUGUUCGCUCAUGCUUGUCGGAAACGUUCGUACGAACAUGAGUGGGCACAAAAGACUCCGUUGCCACGACAAAUCAGGUGAAUCGCGUCGUGGUAUAAAGCAUACAAACAAUUUCAUUUUCACAACUACUGGCCGUCGGCCACAGACCUGCUGUCGAAAUAGGACGCUGUUGCUUGCUUUGUUCGGCGGAAGUGGACGUACAGGUAAGCGCCCCGUCACGGUAAGCGAGAUGCUAUUAUAUCAGCGAUGUUGUAUUAAGUCUGAAGACUCAAUGACGGUCGCGUUCCGAGCCCUGCCGAGGUCCGUGACAGGAGAUAGUGUCCUCUCUGUAUACAGGCCAAAAAUACAAGUCUUCAAUCGGUACGCAGCAGUAUUUCGAAAGCGAUCCCGUGUUAAGGAAACCUACCAAGGUCAGUGUGUUUUAAUCGCAUUAGCCAGAAUUAAGGAUAGUGUCCUAGGCACCCAACCGCGGAAGAUUUCGAGAUGCUACUUGAAACGUGAGAAGCAAAGUUGCUUCACCUUGUCGGCUGGGGGUGUCAGGUACGAAGCAGAGAAAUAUUGUUUUGUUGUAAAAAGGAUAGUACUCCGAAAGAUCGUCUCUCUGAGAAGAGAUGUGAGAGGCAGGGAUUCUAAGGCUCAUAUCACCAAGCCAAGCCGUCUAGGAGAAACUGCAUUGAGGUCGCCUCCACCAGGCCAAAACGGCCGUCUUGUUGGGAUCCCCAAUGUGCAGAAUCUAUUUAAAGAAGUCCUCGCGAAGAGCACGCUUUGCUUCCGAGAGGCUUAUGUCACCGAUUGGGCAGAUAAUGGCGCGGCUUUCGCACAUCGAGGUGUGGGUACUGACGUCUGUUUUAGAAGAAAAUCAAGCAGCCAGAGUCAAAGUCCUUCCCACUCGGCAAUCCCUUCUUCUGAUUGCACGUUAAUGCCAACUUGGCCCUUCUACCUGUUGAACUGCUCUACAUGCCUGAGUACCGGCGUGCGCCUAAAGCCCUAUAAUAUGGUCGAGAGUUGCCUUAUCUGUGAGCUCUUGGGCGCGCGGACCAGUGCUGGUACGGCGCCAUGCGGGAGAUUCGAUGGCCAGGGUAGGGACCUUAGGGAACCAGGCGAGGCUAGGUCGGGCCAAUCCAAGUCGUUACCAAAACGAACUUCUCACAGGUUAAAGCGGCCCUUCGACUGGAUAGCACCCCCAAUGUCUUACAUCACCCCGAUUAUGUGCAUUCGCAAAAGAUCAAGGACUUCGAUGGUUCGAGGCAGGGACACCUGGCACGGGAUGGGAUCCUUGGAUACUCACAAGCCACUGAAACCGCGGCCUCCAGUAACUCACUCAGUCUCUGACCCCUGGGUAGUGAGCGGCAGAGUCUUUCCUCCCGCGGGGACCCCGAUUUACCUGUGGCUGUCGCCUUUCCGCGGUAGCGUGUGUCUGAGUACUCUGCGGCGGUCAGCUCAAAAUACGUCCCGAUUAAUAUAUUGUGCUUUGAAUUACUCUGAUUGCGUUGGAAUGAAUACCGCGUGCCAGACAGAUAAGGAGCUUUGGGAGAAAGUUACUAAUUGCACUAACGAGGAGCGUGUGCCACGGACUACUGCUGUACCGAUCAGAAGGUGUUACGGGUUUAGUGUGAGAUCCAAACUCUGGGCCACCUCUGUUAAACCCGUGCUUUUGUUAUGUAGAACUUGCACGCUAACCACCAAACAAACAUGUCUGUCAGGUAUUACACAACCACCGGCUCGACAGAGAUUAGCCAGCCUAGGCACAGUAAACAAUUCAGCAGUUUUGGGCUCAUCCGGCAGCGCGCGUCGUCGUGAACUCAGAUUUCUCAUCAUCAUAUUAGGGCAAUCUUCUGUUGACUGCUUCUUCGCUUCCGUUCCUGCGCCGGAAGUGGGUGGGCGAUGGAAAGAUUCCGUACUGCUCCAGCGUGAUGAGAGCAUGAUAGUGAAUUACAGAGUUCAAGGUGGAGUUGCCGACAUACUAACGGCUCGUUGGAAAGACGGGCCAUCUCUACUGACUAAGAUCAUAGAGAUUUGGAUAGUCGUGAUUGGUGGCUGCUAUCCGAUGAUAAGGCGUACGCGAAAUUUAUUCUGCAGGCACGUUAUAGAUUCAUAUAACCUUCUCAAGAUUUUUUCGUAUGUUUACUUUAGAUUUCAUCUGCGGCUUAAAAUCAAGUGCCUGAGAUCCCUUGCCACCAAAGCCACUUUCAUAUGCCCCACUUACUCUUGUUGGCGUAGCGCAUCUUGGGAGCCGUCCGAACGCCAACUACUGGUAUGUCAUGUCGGAUCUGGCGUUCAAUGCGUAAUGCUGGGUGAACAGUAUGCACGCUGCCCUACUGACCAUCGCUGGGUCACUCACGACUUUACAGAAAACCACGCCCGAGAACGAGCUUGCUGUGCGUUCUCUUUACUCAUAGGGGGGUGUACAAGUUGCCCGGCGCGUUCAUUAGUGGUCUUGAAGCGUGAUGACUUUUCCAAGUGGGUUUCCGGGCAAAGAUUUGUAUUUGCCCGGCAAGACCGAGUGCUUCCGCAGCGUGAGCAUGACCCUGACGACAGCCUGGUGCCGGCAUCGAUAGAGAGAUACAAAACAGUACUACCUAAACGAAUGCCACGUUCCAGUCCCGAGCUUGUCUCGCGCCGCGGUCCUCGGUGUGGUUUAGACAGCUGCCUACAAGGGGUCACGUUAUUCUCGAGUAACGAUCGCCUGACACGAAGGGGGACGAAGUCAGUUUGCGAGAAUAGAAUCGCGGGGCCACUCCAAACACUGGCUAGCGUUCGUUAUAAUAGCAGAGAACAACGAUCUCUUACGUUAUGUGGCGAAUAUACGCCCGAGUCCCUUACCAUGGUUUUGAAAUUGGACGGGCACUACCAGCGCAUGCUGAGCCACUUAGAAAGAACACCAGAGUCAAAUGUAAUCCUACGAAACUCAGGUGUUACAAAACGCGAUAGCGAAGCCUGUGUAUUAGCCGUUCAACAAGUUCGGGAUAGGUCGAAUGGUCAUCCUAGAAUAAGGGUUCUGGGCAGUGGGGGAGCGGAGAUCAUAGGAAUGAGUACUAUUUCAGCCCGAGACGAACACAAUGCUGAAGCGGAUGCUAGGCCCAAGUUAUCCUUCAACGAUGCAGGGCGAGUGGCCACCGAGACAGGUGCGUGGAGUAUCUUUGAAACCAAACUUGCAUUUUGUGACCACGACGAUUUGGGUACAAUUAAUUACUUUUCGGGCAGUUUCUCUACCCCCAACCAAGAGAUUCACACCCGUCCUUUACGUGUUAUGAAACUCGUCGUGCCUCAGACUUAG'

fcd = ['UUU', 'UUC']
scd = ['UCU', 'UCC', 'UCA', 'UCG', 'AGU', 'AGC']
ycd = ['UAU', 'UAC']
stopcd = ['UAA', 'UAG', 'UGA']
ccd = ['UGU', 'UGC']
wcd = ['UGG']
lcd = ['CUU', 'CUC', 'CUA', 'CUG', 'UUA', 'UUG']
pcd = ['CCU', 'CCC', 'CCA', 'CCG']
hcd = ['CAU', 'CAC']
qcd = ['CAA', 'CAG']
rcd = ['CGU', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG']
icd = ['AUU', 'AUC', 'AUA']
mcd = ['AUG']
tcd = ['ACC', 'ACU', 'ACG', 'ACA']
ncd = ['AAU', 'AAC']
kcd = ['AAA', 'AAG']
vcd = ['GUU', 'GUC', 'GUA', 'GUG']
acd = ['GCU', 'GCC', 'GCA', 'GCG']
dcd = ['GAU', 'GAC']
ecd = ['GAA', 'GAG']
gcd = ['GGU', 'GGC', 'GGA', 'GGG']
print((len(code))/3)

def encode(x):
    y = 0
    ini = 0
    fini = 3
    codon_list = []
    while y < len(x)/3:
        ctcodon = x[ini:fini]
        if ctcodon in fcd:
            codon_list.append('F')
        elif ctcodon in lcd:
            codon_list.append('L')
        elif ctcodon in scd:
            codon_list.append('S')
        elif ctcodon in ycd:
            codon_list.append('Y')
        elif ctcodon in ccd:
            codon_list.append('C')
        elif ctcodon in wcd:
            codon_list.append('W')
        elif ctcodon in lcd:
            codon_list.append('L')
        elif ctcodon in pcd:
            codon_list.append('P')
        elif ctcodon in hcd:
            codon_list.append('H')
        elif ctcodon in qcd:
            codon_list.append('Q')
        elif ctcodon in rcd:
            codon_list.append('R')
        elif ctcodon in icd:
            codon_list.append('I')
        elif ctcodon in mcd:
            codon_list.append('M')
        elif ctcodon in tcd:
            codon_list.append('T')
        elif ctcodon in ncd:
            codon_list.append('N')
        elif ctcodon in kcd:
            codon_list.append('K')
        elif ctcodon in scd:
            codon_list.append('S')
        elif ctcodon in vcd:
            codon_list.append('V')
        elif ctcodon in acd:
            codon_list.append('A')
        elif ctcodon in dcd:
            codon_list.append('D')
        elif ctcodon in ecd:
            codon_list.append('E')
        elif ctcodon in gcd:
            codon_list.append('G')
        else:
            pass
        ini += 3
        fini += 3
        y += 1
    print(''.join(codon_list))

encode(code)